services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - TZ=Europe/Berlin
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - /Users/troy/Downloads:/downloads

# ollama:
#     image: docker.io/ollama/ollama:latest
#     ports:
#       - 7869:11434
#     volumes:
#       - .:/code
#       - ./ollama/ollama:/root/.ollama
#     container_name: ollama
#     pull_policy: always
#     tty: true
#     restart: always
#     environment:
#       - OLLAMA_KEEP_ALIVE=24h
#       - OLLAMA_HOST=0.0.0.0
#     networks:
#       - ollama-docker



volumes:
  n8n_data:
    external: true

